### ISSUE TITLE
hwmlpcconfig - LPC configuration .plist not loaded

### ISSUE THREAD

**Issue by soundflix** [CloverHackyColor/HWMonitorSMC2#14]
I tried to fix the fan names from the generated .plist with hwmlpcconfig. But my renames don't load/show up in HWMonitorSMC2. I guess it is related to the LPC path where I put the plist.
My hwmlpcconfig output file was called "unknownOEM.plist."

hwmlcpconfig v1.2 by vector sigma, 2020
Super IO Chip = Nuvoton NCT679BD
OEM Vendor = Unknown
OEM Board = Unknown
[..sensor info..]

I tried these LPC paths and plist names:
![Bildschirmfoto 2021-03-23 um 12 02 44](https://user-images.githubusercontent.com/80773469/112136769-b371c180-8bcf-11eb-9968-846a79365457.png)

What's wrong?

**Comment by baratta930** [comment]
Make sure you have ExposeSensitiveData set to include 0x08 bit –  Expose OEM information as a set of UEFI variables. Once you do that and reboot then hwmlcpconfig will give the correct info for OEM and name the file/folder correctly.

**Comment by soundflix** [comment]
Thanks baratta930!
I changed ExposeSensitiveData in my config.plist from 6 to 14 an now it works.
