### ISSUE TITLE
Temperature on Navi card with VirtualSMC?

### ISSUE THREAD

**Issue by MacInTheNet** [CloverHackyColor/HWMonitorSMC2#17]
Hello, please could you tell me if I can get the temperature of a 5500XT when I use VirtualSMC?
Just need to know if it's impossible or there is a way because I can only see VRAM data and nothing else on HWMonitorSMC2 
:(
Thanks

**Comment by ed006949** [comment]
> Hello, please could you tell me if I can get the temperature of a 5500XT when I use VirtualSMC?

+1

**Comment by SergeySlice** [comment]
Use FakeSMC instead.
