### ISSUE TITLE
Enabling Fan Control

### ISSUE THREAD

**Issue by JanX2** [CloverHackyColor/HWMonitorSMC2#4]
I have been looking through the code and managed to angle the fan control UI by replacing `.systemLog` with `.fanControl` everywhere. Just to check what would happen. I got the UI, can enable PWM and change the value, even get a user authentication dialog, but it doesn’t work properly: the RPM value of the fan doesn’t actually change.

Please fix fan control. It would be of great help to lower noise on my machine.

**Comment by vectorsigma72** [comment]
Hi, changing .systemLog to .fanControl brings you to no where because is not the app that needs to be changed, but your drivers instead that must support needed smc keys.

**Comment by JanX2** [comment]
I’m aware of that. I just wanted to enable the GUI and see how far I could get in debugging fan control on my machine. 

On macOS 10.12.6 I got fan control to work using [RehabMan’s FakeSMC](https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek/downloads/RehabMan-FakeSMC-2018-0915.zip). I can’t get there on any later macOS release.

Do you have any pointers for me to learn more of what necessary to debug this issue?

**Comment by JanX2** [comment]
Finally got what you meant: you have to use HWMonitorSMC2 in conjunction with [FakeSMC3](https://github.com/CloverHackyColor/FakeSMC3_with_plugins)!
